# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-22 07:20
from __future__ import unicode_literals

import apps.employees.models.employee
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=128, verbose_name='first name')),
                ('last_name', models.CharField(max_length=128, verbose_name='last name')),
                ('middle_name', models.CharField(blank=True, default='', max_length=128, verbose_name='middle name')),
                ('notes', models.TextField(blank=True, default='', verbose_name='notes')),
                ('birthday', models.DateField(blank=True, default=None, null=True, verbose_name='birthday')),
                ('work_started', models.DateField(default=apps.employees.models.employee.current_date, verbose_name='work started')),
                ('phone_number', models.CharField(blank=True, default='', max_length=128, verbose_name='primary phone')),
                ('additional_phone_number', models.CharField(blank=True, default='', max_length=128, verbose_name='additional phone')),
                ('contact_email', models.EmailField(blank=True, default='', max_length=254, verbose_name='email')),
            ],
            options={
                'verbose_name': 'employee',
                'verbose_name_plural': 'employees',
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512, unique=True, verbose_name='name')),
            ],
            options={
                'verbose_name': 'position',
                'verbose_name_plural': 'positions',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512, unique=True, verbose_name='name')),
            ],
            options={
                'verbose_name': 'specialization',
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='employees.Position', verbose_name='position'),
        ),
        migrations.AddField(
            model_name='employee',
            name='specializations',
            field=models.ManyToManyField(blank=True, related_name='employees', to='employees.Specialization', verbose_name='specializations'),
        ),
    ]
