# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-20 13:22
from __future__ import unicode_literals

import apps.employees.models.employee
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='work_started',
            field=models.DateField(default=apps.employees.models.employee.current_date, verbose_name='work started'),
        ),
        migrations.AlterField(
            model_name='position',
            name='name',
            field=models.CharField(default='', max_length=512, unique=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='specialization',
            name='name',
            field=models.CharField(default='', max_length=512, unique=True,
                                   verbose_name='name'),
        ),
    ]
