# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-17 12:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_primary', models.BooleanField(default=False, verbose_name='is primary')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_contact_list', to='employees.Employee', verbose_name='employee')),
            ],
            options={
                'verbose_name': 'email',
                'verbose_name_plural': 'emails',
            },
        ),
        migrations.CreateModel(
            name='GitAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_primary', models.BooleanField(default=False, verbose_name='is primary')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('account', models.CharField(max_length=32, verbose_name='number')),
                ('url', models.CharField(max_length=32, verbose_name='url')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gitaccount_contact_list', to='employees.Employee', verbose_name='employee')),
            ],
            options={
                'verbose_name': 'phone number',
                'verbose_name_plural': 'phone numbers',
            },
        ),
        migrations.CreateModel(
            name='PhoneNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_primary', models.BooleanField(default=False, verbose_name='is primary')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('number', models.CharField(max_length=32, verbose_name='number')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phonenumber_contact_list', to='employees.Employee', verbose_name='employee')),
            ],
            options={
                'verbose_name': 'phone number',
                'verbose_name_plural': 'phone numbers',
            },
        ),
        migrations.CreateModel(
            name='Skype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_primary', models.BooleanField(default=False, verbose_name='is primary')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('login', models.CharField(max_length=32, verbose_name='skype login')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skype_contact_list', to='employees.Employee', verbose_name='employee')),
            ],
            options={
                'verbose_name': 'skype account',
                'verbose_name_plural': 'skype accounts',
            },
        ),
    ]
